import { Puzzle, ScoreRankings } from "./gameTypes";

export const emojisToScores: { [key in ScoreRankings]: string } = {
  Beginner: "😴",
  "Good Start": "😐",
  "Moving Up": "🙂",
  Good: "😃",
  Solid: "😚",
  Nice: "😎",
  Great: "🤩",
  Amazing: "🔥",
  Genius: "🧠",
  "Queen Bee": "🐝",
};

export const dummyPuzzle: Puzzle = {
  gameId: "8754b810-3d36-41b5-9f1a-e54ebc4c3793",
  date: "2022-09-23T04:00:00.456Z",
  puzzleLetters: ["a", "d", "e", "i", "l", "r", "y"],
  centralLetter: "i",
  pangrams: ["DREARILY", "READILY"],
  solutionsWithScores: {
    AERIAL: 6,
    AERIALLY: 8,
    AERIE: 5,
    AIDE: 1,
    AIDED: 5,
    AILED: 5,
    AIRED: 5,
    AIRIER: 6,
    AIRILY: 6,
    AIRY: 1,
    ALLIED: 6,
    ARIA: 1,
    ARID: 1,
    ARIDLY: 6,
    DAILY: 5,
    DAIRY: 5,
    DALLIED: 7,
    DALLIER: 7,
    DEADLIER: 8,
    DEARIE: 6,
    DELI: 1,
    DELIRIA: 7,
    DERAIL: 6,
    DERAILED: 8,
    DERIDE: 6,
    DERIDED: 7,
    DERRIERE: 8,
    DIAL: 1,
    DIALED: 6,
    DIALLED: 7,
    DIARY: 5,
    DIDDLE: 6,
    DIDDLED: 7,
    DIDDLER: 7,
    DIED: 1,
    DILL: 1,
    DILLY: 5,
    DILLYDALLIED: 12,
    DILLYDALLY: 10,
    DIRE: 1,
    DIRELY: 6,
    DIRER: 5,
    DREARIER: 8,
    DREARILY: 15,
    DRIED: 5,
    DRIER: 5,
    DRILL: 5,
    DRILLED: 7,
    DRILLER: 7,
    DRILY: 5,
    EARLIER: 7,
    EDDIED: 6,
    EERIE: 5,
    EERIER: 6,
    EERILY: 6,
    EIDER: 5,
    ELIDE: 5,
    ELIDED: 6,
    EYELID: 6,
    EYRIE: 5,
    IDEA: 1,
    IDEAL: 5,
    IDEALLY: 7,
    IDLE: 1,
    IDLED: 5,
    IDLER: 5,
    IDLY: 1,
    IDYL: 1,
    IDYLL: 5,
    ILEA: 1,
    ILIA: 1,
    LADDIE: 6,
    LAID: 1,
    LAIR: 1,
    LAIRD: 5,
    LARDIER: 7,
    LEERIER: 7,
    LIAR: 1,
    LIDDED: 6,
    LIED: 1,
    LIEDER: 6,
    LILY: 1,
    LIRA: 1,
    LIRE: 1,
    RADIAL: 6,
    RADIALLY: 8,
    RADII: 5,
    RAID: 1,
    RAIDED: 6,
    RAIDER: 6,
    RAIL: 1,
    RAILED: 6,
    RAILLERY: 8,
    RALLIED: 7,
    READIED: 7,
    READIER: 7,
    READILY: 14,
    REDIAL: 6,
    REDIALED: 8,
    REDIALLED: 9,
    REDID: 5,
    REEDIER: 7,
    RELAID: 6,
    RELIED: 6,
    RIAL: 1,
    RIDDED: 6,
    RIDDLE: 6,
    RIDDLED: 7,
    RIDE: 1,
    RIDER: 5,
    RILE: 1,
    RILED: 5,
    RILL: 1,
    RIYAL: 5,
    YIELD: 5,
    YIELDED: 7,
  },
  rankingScheme: {
    Beginner: 0,
    "Good Start": 11,
    "Moving Up": 29,
    Good: 47,
    Solid: 88,
    Nice: 148,
    Great: 237,
    Amazing: 296,
    Genius: 415,
    "Queen Bee": 593,
  },
};
